Vorschlag für ein anderes Modifier-Konzept
zweitag/html-css-guidelines pull request #15
Opened 2020-10-27 09:27 UTC by jkimmeyer

Wir haben uns gestern im HTML/CSS-Austausch über die leicht unterschiedlichen Modifier Konzepte in ZASAF und den Whitelabel Components unterhalten.

In diesem Fall haben wir uns darauf geeinigt, dass wir das Konzept mit den Prefixen `is` oder `has` sinnvoller finden. 
Folgende Gründe sprechen für die Umbenennung: 
- Identifizierung von Modifiern wird einfacher (z.B. auch die Suche nach `has-` oder `is-` innerhalb von Dateien)
- der aktuell gelebte Standard in Zweitag Projekten ist das Konzept mit `is-` bzw. `has-`
- nicht alles ist per einfachem Adjektiv möglich: gerade bei solchen Neologismen wie `submenued` kann es zu Unklarheiten führen, wenn man zusätzlich noch eine `submenu` Komponente besitzt.

Gegen die Umbenennung spricht, dass `is-` und `has-` keinen Vorteil für die individuelle Semantik eines Modifier enthalten. 

Ein Alternativvorschlag wäre, die Modifier per Zeichen zu trennen, z.B. `button | primary` o. `button [ primary disabled ]`. Damit würde man, neben den oben genannten Vorteilen, auch dem Nachteil der Umbennenung entgegenwirken.

2020-11-05 08:24 UTC, ChristianPeters requested changes

2020-11-05 08:24 UTC, ChristianPeters commented on README.md
> -* ist idealerweise ein einfaches Adjektiv
Das stimmt ja jetzt nur noch halb. Bitte definieren, wann is (Adjektiv) und wann has (Nomen)

2020-11-05 08:24 UTC, ChristianPeters commented on README.md
> +* die Prefixe werden benötigt, damit ein Modifier einfach identifiziert werden kann und Zustände abgebildet werden können, für die Adjektive nicht ausreichend sind
Beispiele machen es klarer. Es gibt noch gar kein Beispiel für has.

2020-11-05 08:25 UTC, ChristianPeters commented
Ich muss das dann nicht noch einmal reviewen, gerne einfach mergen. 🙂

2020-11-11 07:29 UTC, SimonEggert approved these changes

2020-11-12 13:23 UTC, merged