Rework Sass-Styleguide
zweitag/html-css-guidelines pull request #2
Opened 2017-06-21 15:14 UTC by rastersysteme

2017-06-21 15:15 UTC, rastersysteme commented
@ChristianPeters Ich habe das ganze ein wenig angepasst und erweitert. Magst du schon mal drüber schauen und mir Feedback geben bzw. sagen, was dir noch fehlt?

2017-06-21 16:39 UTC, ChristianPeters requested changes

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +Bei der Arbeit an großen, langlebigen Projekten mit mehreren Entwicklern unterschiedlicher Fähigkeiten ist es wichtig, dass wir alle einheitlich arbeiten. Unsere oberste Prämisse sollte sein, dass un
* [x] Bei "unterschiedlicher Fähigkeiten" könnte man sich angegriffen fühlen: "_Oh, meint er mich damit, bin ich ihm nicht gut genug?_ "

* [x] warum "_aber_ transparent und lesbar"?

* [x] _Empfehlungen_? Wenn du das so sagst, ist es auch in Ordnung es anders zu machen. "Guidelines"?

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +1. **von außen nach innen**: ZASAF folgend beginnt man in der Regel mit dem Page-Wrapper-Element.
* [x] Was für ein Page-Wrapper-Element? Das kommt doch noch aus meinem alten System, darüber hat in diesen Guidelines ja noch niemand etwas gesagt.

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +.main-navigation--item
* [x] Wie jetzt, ein zweiter Block zu `.main-navigation--item`?

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +  &.highlight
* [x] Das ist doch ein Modifier, oder? Dann sollte er `.highlighted` heißen.

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +  .highlight > &
* [x] Was ist `.highlight`? Es klingt inhaltlich wie ein Modifier und sollte dann nicht allene stehen.

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +Eine der einfachsten Formen eines Styleguides ist ein Set von Regeln bezüglich Syntax und Formatierung zu definieren, so dass alle Entwickler eine gemeinsame Basis haben und der Code gut zu lesen ist
* [x] Der erste Teilsatz ist sprachlich nicht im Reinen. Du könntest "Eine der einfachsten Formen … ist es, …" schreiben. Vielleicht besser?:

> Die Basis eines gemeinsam gelebten Stils ist ein grundlegendes Set an Syntax- und Formatierungsregeln. Eine strikte Einhaltung bringt Effizienzpotenziale, weil man Code schneller lesen, verstehen und abgleichen kann. Es ist weniger wahrscheinlich, dass man Dinge übersieht oder missversteht und niemand verbringt Zeit damit, seinen Arbeitsbereich durch Umformatierungen "für sich einzurichten".

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +- Multi-Line-Stil: Ein Selektor pro Zeile, eine Deklaration pro Zeile
Das ist etwas anstrengend zu lesen. Du hast mir ja das Beispiel gezeigt, wo rechts neben der Regelliste ein zusammengefasstes Beispiel zu sehen war. Hast du dich dagegen entschieden, das als Tool zu nutzen und den Styleguide dann hier einfach nur zu verlinken?

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +- Selektorverschachtelung: maximal drei Ebenen tief
> …, nach Möglichkeit jedoch vermeiden und eine eigene Klasse für Elemente einer Komponente einführen

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +- Alle Bezeichnungen werden auf englisch und klein geschrieben. Setzt man mehrere Wörter zu einem Selektor zusammen, trennt diese ein Bindestrich: `.data-table`.
* [x] *`man`

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +Um nicht ständig nach einer CSS-Eigenschaft suchen zu müssen, verwenden wir eine feste Deklarationsreihenfolge. Sie ist in logische Blöcke gegliedert, die man sich im Detail in der Linter-Config (TOD
* [ ] verlinken

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +- z.B. box-sizing, width, height, margin, border, padding, transform
* [ ] Die Beispiele sollten ja auch schon in der Reihenfolge sein wie sie im Detail vorgegeben ist. Und hier würde ich von außen nach innen erwarten: `width, height, padding, border, margin`
* Warum transform hier? Die Prozentangaben sind zwar abhängig von den Ausmaßen der Box. Aber verwendet man das nicht am häufigsten zur Bewegung im Raum und würde daher eher unter 4. passen?

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +#### Vermeide Elementselektoren
* [ ] Wir haben hier einen Namenskonflikt: Sowohl die HTML-Basiselemente als auch die Komponentenelemente (E in BEM) sind Elementselektoren. Wollen wir erstere anders/konkreter benennen?

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +## Inhaltsverzeichnis
* [ ] Einträge bitte verlinken

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +### Coding Konventionen
* [ ] Unten aufgeführte Coding-Konventionen sind nicht bloß Syntax. Daher müsste man eigentlich das hier auf die 2. Überschriften-Ebene bringen
* [ ] Die Coding-Konventionen sind aber auch so ne zu lange Liste an Dingen, die nicht gut genug strukturiert sind, als dann man gut navigieren / sie sich gut merken kann.

Willst du vielleicht `## Selektorregeln` rausziehen?

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +#### Vermeide den selben Selektor fürs Styling (CSS) und fürs Verhalten (JS) zu verwenden
* [ ] Das habe ich immer gegenteilig gehandhabt, da ich Komponenten als Ganzes inklusive Styling und JavaScript verstanden habe. Vue.js folgt doch auch der Mentalität, das zusammenzuhalten. Wie siehst du das, @stsc3000?

  Wenn wir diesen Punkt nicht schnell klären können, würd ich ihn lieber rausziehen aus diesem PR.

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +Einfach weil es kürzer und einfacher zu lesen ist.
* [ ] Das ist mir ein bisschen zu salopp und inhaltsleer. Wer's nicht kennt, für den ist es schwieriger zu lesen. Aber das ist weit verbreitete Praxis, die keiner Erklärung Bedarf. Können wir auch einfach streichen den Satz.

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +Die Zahlen 100, 200 … 900 sind typografischer Standard. Außerdem sind sie kürzer und sparen ein paar Bits ein. ;)
* [ ] Das 1 Zeichen ist lächerlich. An anderer Stelle erlauben wir uns viel inperformantere Praktiken, die auch nicht Erwähnung finden. Triftiger ist doch das Argument, dass man mit der Zahlen-Darstellung besser differenzieren kann und auch nicht mal "bold" und mal "600" schreiben möchte.

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +Zum Testen unseres Sass-Codes benutzen wir [Sass Lint](https://github.com/sasstools/sass-lint). Der Linter sollte am Ende keine Fehler oder Warnungen ausspucken.
* [ ] Ende = Projektende = Projekt wird übergeben oder eingestampft und dann ist es uns eh egal? :) Hier sind genauere Richtlinien von Nöten, wann der Linter ohne Fehler und wann ohne Warnungen durchzulaufen hat plus Best Practices

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +```
* [ ] Syntax-Highlighting fehlt

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +```
* [ ] Syntax-Highlighting fehlt

2017-06-21 16:39 UTC, ChristianPeters commented on sass-style-guide.md
> +## Editorconfig
* [ ] Typo: EditorConfig

2017-06-22 05:37 UTC, rastersysteme commented on sass-style-guide.md
> +Bei der Arbeit an großen, langlebigen Projekten mit mehreren Entwicklern unterschiedlicher Fähigkeiten ist es wichtig, dass wir alle einheitlich arbeiten. Unsere oberste Prämisse sollte sein, dass un
@ChristianPeters Ich wollte ein deutsches Wort für _Guidelines_ nehmen und da klang _Empfehlungen_ freundlicher als _Handlungsanweisungen_. Was hältst du von _Richtlinien_ oder _Vorgaben_?

2017-06-22 05:41 UTC, rastersysteme commented on sass-style-guide.md
> +1. **von außen nach innen**: ZASAF folgend beginnt man in der Regel mit dem Page-Wrapper-Element.
@ChristianPeters Es gibt in der Regel immer ein Page-Wrapper-Element, in das die Komponenten gepackt werden. Bei mir ist das `.page`.

2017-06-22 05:43 UTC, rastersysteme commented on sass-style-guide.md
> +  &.highlight
Good catch!

2017-06-22 05:43 UTC, rastersysteme commented on sass-style-guide.md
> +.main-navigation--item
Copy/Paste-Fehler :/

2017-06-22 05:48 UTC, rastersysteme commented on sass-style-guide.md
> +  .highlight > &
@ChristianPeters Ja, `.highlighted` ist ein Modifier. Aber warum darf er nicht alleine stehen?

**Variante 1:**

``` sass
.main-navigation--item
  &.highlighted
    bacground-color: $color-background-loud

.main-navigation--link
  .highlighted > &
    color: $color-text-inverted
```

vs.

**Variante 2:**

``` sass
.main-navigation--item
  &.highlighted
    bacground-color: $color-background-loud

.main-navigation--link
  .main-navigation--item.highlighted > &
    color: $color-text-inverted
```

vs.

**Variante 3:**

``` sass
.main-navigation--item
  &.highlighted
    bacground-color: $color-background-loud
    .main-navigation--link
      color: $color-text-inverted

.main-navigation--link
  …
```

Bei Variante 3 steht die Eigenschaft nicht beim Link, wo sie meines Erachtens hingehört. Daher ist das die schlechteste Vorgehensweise. Bei Variante 2 überqualifiziere ich den Selektor, den ich später im CSS nicht brauche. Daher bin ich für Variante 1.

2017-06-22 06:25 UTC, rastersysteme commented on sass-style-guide.md
> +Eine der einfachsten Formen eines Styleguides ist ein Set von Regeln bezüglich Syntax und Formatierung zu definieren, so dass alle Entwickler eine gemeinsame Basis haben und der Code gut zu lesen ist
👍

2017-06-22 06:28 UTC, rastersysteme commented on sass-style-guide.md
> +- Multi-Line-Stil: Ein Selektor pro Zeile, eine Deklaration pro Zeile
@ChristianPeters Nein, ich habe mich nicht dagegen entschieden. Ich wollte nur erst einmal alles Relevante in die Datei packen. Fürs Styling war gestern keine Zeit mehr. Ich schau heute, was sich da rausholen lässt.

2017-06-22 06:29 UTC, rastersysteme commented on sass-style-guide.md
> +- Selektorverschachtelung: maximal drei Ebenen tief
👍

2017-06-22 06:32 UTC, rastersysteme commented on sass-style-guide.md
> +- Alle Bezeichnungen werden auf englisch und klein geschrieben. Setzt man mehrere Wörter zu einem Selektor zusammen, trennt diese ein Bindestrich: `.data-table`.
@ChristianPeters Verstehe nicht ganz, was du meinst. Willst du sagen: »…, trennt man diese durch einen Bindestrich: …«?

2017-06-22 06:57 UTC, rastersysteme commented on sass-style-guide.md
> +- z.B. box-sizing, width, height, margin, border, padding, transform
@ChristianPeters 
Zu 1.: Das ist aus meiner Sicht schon die richtige Reihenfolge. Block 1:`width, height` und dann Block 2: `margin, border, padding`. Wenn man bei `box-sizing: border-box` von außen nach innen gehen würde, müsste es genau gesagt `margin, width, height, border, padding` lauten, da die Ausmaße `width` und `height` den Rahmen und die Innenabstände inkludieren. Da man aber `margin, border, padding` sowie `width, height` nicht auseinanderreißen möchte, nennt man erst Block 1, weil es die wichtigeren Informationen bereithält und dann Block 2.
Zu 2.: `transform` macht mehrere Dinge und ist daher nicht 100%ig zuzuordnen. Auf der einen Seite gibt es mit `scale, skew, rotate` Eigenschaften, die aus meiner Sicht gut zu 5. passen. Auf der anderen Seite hat man  `translate`, was besser zu 4. passt. Ich habe es letztendlich unter 5. verortet, da ich erst einmal wissen möchte, was ich überhaupt transformieren möchte und dafür brauche ich die Informationen aus dem Box-Model.

2017-06-22 07:16 UTC, rastersysteme commented on sass-style-guide.md
> +### Coding Konventionen
Finde ich gut!

2017-06-22 07:21 UTC, rastersysteme commented on sass-style-guide.md
> +#### Vermeide Elementselektoren
Vorschlag: Basiselementselektor

2017-06-22 07:29 UTC, rastersysteme commented on sass-style-guide.md
> +#### Vermeide den selben Selektor fürs Styling (CSS) und fürs Verhalten (JS) zu verwenden
Wenn man auf _Single File Components_ bei vue.js zurückgreift, hat man auch alles an einem Ort, was es definitiv einfacher macht. Da finde ich es auch sinnvoll! Splitte ich jedoch meinen Code in HTML-, CSS- und JS-Dateien auf, so wie wir es derzeit tun, halte ich den oben beschriebenen Ansatz für gangbarer.

2017-06-22 07:41 UTC, rastersysteme commented on sass-style-guide.md
> +Einfach weil es kürzer und einfacher zu lesen ist.
Ich hab’s abgeändert.

2017-06-22 07:43 UTC, stsc3000 commented on sass-style-guide.md
> +#### Vermeide den selben Selektor fürs Styling (CSS) und fürs Verhalten (JS) zu verwenden
Ich würde das typischerweise trennen: Mir ist es schon mehrmals passiert dass man im Nachhinein festgestellt hat dass eine Änderung die nur das Styling betreffen sollte auch JS Funktionalität zerschossen hat. Imho sind `data-*` Attribute gut geeignet um typische jQuery `$(li[data-role='accordion']").accordion()` Funktionalität zu verdrahten. Typischerweise liegt hier eine größere Distanz zwischen JS Code und HTML, bzw JS Code wird komponentenübergreifend geschrieben.

Bei Architekturen die auf Komponentenbasis arbeiten (`vue` oder ein eigener Ansatz) sehe ich wiederum nur wenig was gegen das Nutzen von Styling Selektoren sprechen würde, da hier die Distanz zwischen JS Code und HTML sehr gering ist.

2017-06-22 07:45 UTC, rastersysteme commented on sass-style-guide.md
> +Die Zahlen 100, 200 … 900 sind typografischer Standard. Außerdem sind sie kürzer und sparen ein paar Bits ein. ;)
OK.

2017-06-22 07:50 UTC, rastersysteme commented on sass-style-guide.md
> +Zum Testen unseres Sass-Codes benutzen wir [Sass Lint](https://github.com/sasstools/sass-lint). Der Linter sollte am Ende keine Fehler oder Warnungen ausspucken.
@ChristianPeters Hierüber hatten wir ja schon gesprochen, Stichwort Commit-Hook/CI-Test. Ich kann den letzten Satz auch erstmal streichen, wenn du dich so sehr daran störst. Bez. der Richtlinie könnte man natürlich einfach sagen, dass es zu keinem Zeitpunkt Fehler oder Warnungen geben darf (wobei mich mich gerade frage, wozu dann überhaupt Warnungen!?).

2017-06-22 07:53 UTC, rastersysteme commented on sass-style-guide.md
> +## Inhaltsverzeichnis
👍

2017-06-22 07:54 UTC, rastersysteme commented
@ChristianPeters Ich bin mit dem ersten Einarbeiten deines Feedbacks durch, habe hier und da aber noch Rückfragen bzw. Disksussionsbedarf. ;)

2017-06-22 08:38 UTC, ChristianPeters commented on sass-style-guide.md
> +Bei der Arbeit an großen, langlebigen Projekten mit mehreren Entwicklern unterschiedlicher Fähigkeiten ist es wichtig, dass wir alle einheitlich arbeiten. Unsere oberste Prämisse sollte sein, dass un
Wir nutzen in unserem Sprachgebrauch doch auch das englische Wort "Guidelines". Richtlinien wäre die beste Übersetzung, aber das ist weniger positiv konnotiert.

2017-06-22 08:40 UTC, ChristianPeters commented on sass-style-guide.md
> +1. **von außen nach innen**: ZASAF folgend beginnt man in der Regel mit dem Page-Wrapper-Element.
Aber das steht ja nur in einer gesonderten Page-Komponente und es trifft nicht mehr auf spezifische Komponenten zu. Aber okay, man versteht das Prinzip.

2017-06-22 10:12 UTC, ChristianPeters commented on sass-style-guide.md
> +- z.B. box-sizing, width, height, margin, border, padding, transform
**Zu 1.:** Äh, ja ich meinte von innen nach außen und war noch auf dem content-box-Trip. Möchte man die Blöcke wirklich nicht auseinaderreißen? Sollte man nicht auch dort mit border-box jetzt neu denken und tatsächlich `margin, width, height, border, padding` schreiben? Das wäre dann doch einfacher, da konsequent außen nach innen.

2017-06-22 10:35 UTC, ChristianPeters commented on sass-style-guide.md
> +  .highlight > &
Das ist eine Grundregel von Modifiern, s. https://github.com/zweitag/html-css-guidelines/blob/master/README.md#modifier:

> steht nie alleine, sondern ist nur in Verbindung mit der Komponente eindeutig

Ein Modifier an sich ist eben nicht eindeutig. Es können viele Dinge `.highlighted` sein. Nun ist die `.main-navigation` immer sehr hoch in der Seitenhierarchie angesiedelt. Aber nimm eine beliebige Liste, die gehighlightete Einträge enthalten kann, die wiederum Inhalt enthalten kann, der gehighlighted sein kann:

``` haml
%ul.articles-list
  %li.articles-list--item.highlighted
    %h3 Hitlers geheimes Silberbesteck gefunden
    %ul.tag-cloud
      %li.tag-cloud--item.highlighted
        %a.tag-cloud--link Hitler
      %li.tag-cloud--item
        %a.tag-cloud--link Sommerflautenunfug
  %li.articles-list--item.highlighted
    %h3 Große Dürre: Werden wir alle sterben?
    %ul.tag-cloud
      %li.tag-cloud--item
        %a.tag-cloud--link Wetter
      %li.tag-cloud--item
        %a.tag-cloud--link Sommerflautenunfug
```

Wenn du jetzt schreibst…:

``` sass
.tag-cloud--link
  &.highlighted
    background-color: yellow
```

… dann sind in obigem Beispiel alle Tag-Cloud-Links gelb hinterlegt, obwohl es nur der mit "Hitler" sein sollte.

Daher die Regel: Modifier dürfen nie alleine stehen. Alternativ müsste man es m.M.n. so machen wie BEM und `%a.tag-cloud--link.tag-cloud--link__highlighted` schreiben oder sowas.

2017-06-22 10:38 UTC, ChristianPeters commented on sass-style-guide.md
> +  .highlight > &
Variante 2 ist für mich die richtige, da der Selektor demnach nicht überqualifiziert ist. Zu Variante 3 gebe ich dir Recht, finde ich auch ungünstiger.

2017-06-22 10:43 UTC, ChristianPeters commented on sass-style-guide.md
> +- Alle Bezeichnungen werden auf englisch und klein geschrieben. Setzt man mehrere Wörter zu einem Selektor zusammen, trennt diese ein Bindestrich: `.data-table`.
Das will ich sagen!

2017-06-22 10:43 UTC, ChristianPeters commented on sass-style-guide.md
> +#### Vermeide Elementselektoren
👍

2017-06-22 10:47 UTC, ChristianPeters commented on sass-style-guide.md
> +#### Vermeide den selben Selektor fürs Styling (CSS) und fürs Verhalten (JS) zu verwenden
@rastersysteme Dann lass uns doch nur das `data-role` festhalten und die ID-Option rauslassen.

2017-06-22 13:38 UTC, rastersysteme commented on sass-style-guide.md
> +  .highlight > &
Die Grundregel
> steht nie alleine, sondern ist nur in Verbindung mit der Komponente eindeutig

habe ich eher so verstanden, dass ich folgendes _nicht_ machen darf:

``` sass
.highlighted
  background-color: yellow
```

In meinem Beispiel steht `.highlighted` demnach auch nicht alleine, sondern bezieht das Nachfahrenelement mit ein. Apropos, Ich nehme an, in deinem obigen Sass-Beispiel meinst du eigentlich:

``` sass
.tag-cloud--link
  .highlighted &
    background-color: yellow
```

In dem Fall versteh ich deinen Einwand, das wäre Mist. Wenn du dir mein Beispiel oben aber nochmal näher anschaust, dann habe ich ein `>` benutzt, was das Problem löst.

Ich finde übrigens auch, dass

``` sass
.tag-cloud--link
  .tag-cloud--item.highlighted &
    background-color: yellow
```

schwerer zu lesen ist. Der Modifier, auf den es mir letztendlich ankommt, geht unter.

Und ja, an dieser Stelle wünscht man sich BEM. Hier würde der hervorgehobene Link eindeutig mittels `tag-cloud__link--highlighted` selektiert werden können. Ach, wie war das nochmal mit _CSS Modules_? ;)

2017-06-22 14:01 UTC, rastersysteme commented on sass-style-guide.md
> +- z.B. box-sizing, width, height, margin, border, padding, transform
Konsequenter vielleicht, aber schlechter zu erfassen. Ich glaube, wir würden jeden Frontendentwickler, der das nicht erst seit gestern macht, damit vor den Kopf stoßen.

2017-06-22 14:39 UTC, rastersysteme commented on sass-style-guide.md
> +#### Vermeide den selben Selektor fürs Styling (CSS) und fürs Verhalten (JS) zu verwenden
Done.

2017-09-06 12:25 UTC, ChristianPeters commented on sass-style-guide.md
> +    bacground-color: $color-background-loud
* [ ] Typo

2017-09-06 12:25 UTC, ChristianPeters commented on sass-style-guide.md
> +  .highlight > &
Okay, `>` löst genau dieses Problem hier technisch. Aber wie einfach ist das mal zu übersehen oder zu vergessen? Auch wenn es dir nicht passieren würde, es ist schon subtil und wenn man sich der Tragweite nicht bewusst es, kommt der Autor nicht drauf es zu schreiben und ein Reviewer übersieht es vielleicht beim Durchgucken.

Und was machst du, wenn da mehrere Elemente noch dazwischenstehen?

Hier bin ich der Meinung, dass du hier zu sehr für diesen Fall optimierst zu einem hohen Preis. Einfache Regeln sind sehr wertvoll. "darf nie" ist sehr viel einfacher als "soll nicht, es sei denn …".
Wenn du schon zustimmst, dass man sich an dieser Stelle BEM wünscht, dann spricht das doch auch für die explizitere Variante 2?

2017-09-06 12:45 UTC, ChristianPeters requested changes
Es sind noch 2 Themen und 2 kleine To-Dos offen:

Themen:

1. Modifier dürfen nie alleine stehen – oder manchmal doch?
2. Linter: Verwendungsregel und -hilfe (Config)

Offene To-Dos:

* "Guidelines" statt "Empfehlungen"
* Typo (s.o.)

2017-09-06 13:21 UTC, rastersysteme commented on sass-style-guide.md
> +  .highlight > &
Auch wenn ich aufgrund von Lesbarkeit und weniger CSS-Code immer noch meine Variante bevorzuge, so ist das Argument mit den Elementen dazwischen kein so schlechtes wenn ich ehrlich bin. Ich könnte jetzt zwar ausholen und sagen, dann muss man eben die Architektur umstricken, aber das führt zu weit. Ich will endlich fertig werden hier. Daher können wir es gern zu handhaben. Ich würde den PR #3 gleich mergen.

2017-09-06 13:32 UTC, rastersysteme commented
@ChristianPeters 
> Linter: Verwendungsregel und -hilfe (Config)

Das würde ich im Sass Linting PR im anderen Repo gern abhandeln. Dort ist ja auch noch ein Kommentar von dir _offen_, den ich angehen muss. Wenn das für dich OK ist, kannst du den hier gern mergen.

2017-09-06 16:54 UTC, ChristianPeters commented on sass-style-guide.md
> +  .highlight > &
Es geht mir vor allem darum, das System nicht zu kompliziert zu machen. Je ausgefeilter das Regelwerk desto unwahrscheinlicher ist eine 100%-Einhaltung durch alle Anwender.

Wenn in einer Diskussion eine Tradeoff-Entscheidung zwischen mehreren Varianten getroffen werden muss (Explizierung dessen was gemeint ist vs. dadurch entstehendes visuelles Rauschen), und die unterschiedlichen Positionen aus einer anderen Gewichtung der Präferenzen entsteht, find ich es gut, wenn im Zweifel die einfachere Lösung gewinnt.

Und hier würde ich sagen: "Bei Modifier immer Selektor von der modifizierten Komponente davor" ist einfacher als wenn man darauf achten muss, Kindselektoren einsetzbar zu machen.

2017-09-06 17:01 UTC, ChristianPeters requested changes

2017-09-06 17:01 UTC, ChristianPeters commented on sass-style-guide.md
> +  .highlighted > &
* [ ] Änderst du das dann bitte noch?

2017-09-06 17:01 UTC, ChristianPeters commented on sass-style-guide.md
> +Zum Testen unseres Sass-Codes benutzen wir [Sass Lint](https://github.com/sasstools/sass-lint). Der Linter sollte am Ende keine Fehler oder Warnungen ausspucken.
* [ ] Nach wie vor ist noch undefiniert, wann gelintet werden soll. Das steht auch im Rails Template PR nicht. Wann machst du das denn? Hast du einen Pre-Commit-Hook? Gibt's nen Tool, um es als PR-Check hinzuzufügen?
* [ ] Hier fehlt dann auch noch der Link zur Config

2017-09-07 07:31 UTC, rastersysteme commented
Derzeit linte ich meine Sass-Dateien automatisch in Sublime Text, damit sie noch vor dem Comitten korrekt ins Repo wandern. Man könnte auch überlegen, ob man Travis das testen lässt. Was ist da deine Präferenz?

2017-09-07 08:29 UTC, ChristianPeters commented
> Derzeit linte ich meine Sass-Dateien automatisch in Sublime Text, damit sie noch vor dem Comitten korrekt ins Repo wandern. Man könnte auch überlegen, ob man Travis das testen lässt. Was ist da deine Präferenz?

Ich glaube, man braucht beides: sowohl eine lokale Lösung, zumindest für Frontendler, damit die Fehler frühestmöglich erkannt werden als auch einen PR-Check, um sicherzugehen, dass keine Violations in Master kommen.

PR-Check könnte Travis CI sein oder ein extra Dienst, der die Violations z.B. als Kommentare an entsprechende Code-Zeilen schreibt. Ich glaube, das ist im Endeffekt praktischer als ein failender Travis-Build. Kostet mit ca. 10$/Repo aber auch ordentlich. Primärer Anbieter wäre https://houndci.com/, nicht wirklich günstigere Alternative https://sideci.com/ und dann noch das "Ungetüm" CodeClimate.

@hzeus @stsc3000 Wie weit seid ihr damit bei Ruby?

@rastersysteme Willst du vielleicht mal bei DZF die TravisCI-Konfig ausprobieren? Vielleicht kommen wir ja auch damit aus.

2017-09-07 08:41 UTC, hzeus commented
Wir haben bei Ruby noch keine eine automatisierte PR-Lösung geplant, das läuft im Moment noch auf freiwilliger Basis auf den Entwickler-Rechnern.

Wenn ihr für sass eine Lösung sucht, wäre es natürlich sinnvoll, wenn die direkt beides kann.

2017-09-07 08:43 UTC, rastersysteme commented
Mein Vorschlag wäre auch Hound CI. So hätte man auch eine Lösung für Rubocop.

2017-09-07 13:44 UTC, ChristianPeters approved these changes

2017-09-07 13:50 UTC, merged

2017-09-07 13:51 UTC, ChristianPeters commented
Okay, kann jetzt gemergt werden.

* Die Struktur des Repos ist aber dadurch noch nicht ganz im Reinen. Wir haben auf der Startseite auch noch Selector Best Practices. Ich denke, es muss nicht alles hier in der einen Datei sein.

* Bei den Selector Best Practices verweisen wir noch auf externe Links. Darüber hatten wir ja mal gesprochen, oder? Während ich es gut finde, Räder nicht neu zu erfinden, sollte man doch auch Content lieber im Sinne eines Zitats übernehmen, wo dann aber auch klar ist, was davon gutgeheißen wird und was nicht. Die Quelle sollte dann freilich verlinkt werden.

Ich lege dafür mal Issues an.