Resolve external links
zweitag/html-css-guidelines pull request #9
Opened 2017-09-20 07:06 UTC by rastersysteme

Fixes #5
(Waiting for parent #8)

2017-11-24 11:13 UTC, ChristianPeters requested changes
Ich glaube, es ist sehr viel zielführender, nicht nur das Fazit als Regeln aufzuerlegen, sondern insbesondere die eigentliche Problematik vor Augen zu führen. Die richtige Überzeugung zu erlangen ist sehr viel besser als stumpfe Regeltreue. Wir wollen ja Mitarbeiter anleiten, die Regeln zu reflektieren und in der Zukunft weiterzuentwickeln. Dafür reicht kein "um uns das Leben leichter zu machen, machen wir's so!".

Jetzt ist es aber vielleicht auch nicht sinnvoll, die längliche Ausführung in http://cssguidelin.es/#specificity zu übernehmen. Schau mal, dass du das mit ner kleinen Motivation passend verlinkst.

2017-11-24 11:13 UTC, ChristianPeters commented on sass-style-guide.md
> -  * Falls die Editor-Integration keine Option sein sollte, bliebe auch die Möglichkeit eines Pre-Commit-Hooks.
Warum streichst du das? Für den Fall, dass es keine Editor-Integration gibt, Ist doch wesentlich besser als wenn Travis meckern muss?

2017-11-24 11:13 UTC, ChristianPeters commented on css-best-practices.md
> +* auf eine Verkettung von Selektoren verzichten
Das ist jetzt aus dem Original übernommen, aber passt strukturell nicht hundertprozentig hier rein. Auf manche Dinge gehst du im Folgenden nochmal ein, aber die Punkte/Reihenfolge matchen nicht auf die Abschnitte darunter. Die Regel mit IDs steht auch irgendwo anders… Hm.

2017-11-27 13:25 UTC, rastersysteme commented on sass-style-guide.md
> -  * Falls die Editor-Integration keine Option sein sollte, bliebe auch die Möglichkeit eines Pre-Commit-Hooks.
OK, wandert wieder rein.

2017-11-27 13:43 UTC, rastersysteme commented on css-best-practices.md
> +* auf eine Verkettung von Selektoren verzichten
Stimmt.

2017-11-27 13:43 UTC, rastersysteme commented
Ich möchte bei den CSS Best Practices keinen Frontendentwickler missionieren (müssen) und in einem langen Sermon erklären, was im Detail die Problematik von CSS ist (so wie es Harry Roberts macht). Mir geht es in der Tat hier rein um die Regeln und Best Practices, die man auch in dieser Form ohne weiteres reflektieren kann und soll.

Zudem sehe ich eine Gefahr bei einer Verlinkung seiner Seite, denn in einigen Dingen sind unsere Ansätze nicht deckungsgleich. Das könnte zu Missverständnissen führen, wenn man über http://cssguidelin.es/#specificity hinausliest.

Ich werde den Anfang aber noch einmal umschreiben und die Listenpunkte in die Selektorregeln einarbeiten.

2017-12-04 14:16 UTC, ChristianPeters approved these changes

2017-12-04 14:21 UTC, ChristianPeters commented
Okay. Ich bin immer noch nicht ganz davon überzeugt, dass wir mit diesen Inhalten nicht nur für klare Regeln, sondern auch für Verständnis sorgen. Aber es stimmt, dass z.B. das Thema Selektorspezifität ein Grundlagenthema ist. Vielleicht magst du es im Getting Started EDU noch nach https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity verlinken mit dem Hinweis, dass sich die übrigen Guidelines nicht alle mit unseren decken?

2017-12-05 17:20 UTC, rastersysteme commented
> Vielleicht magst du es im Getting Started EDU noch nach https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity verlinken mit dem Hinweis, dass sich die übrigen Guidelines nicht alle mit unseren decken?

Die Verlinkung besteht bereits. Was genau meinst du mit:
*…, dass sich die übrigen Guidelines nicht alle mit unseren decken?*

2017-12-05 17:49 UTC, ChristianPeters commented
Ich habe mich missverständlich ausgedrückt. Ich meine mit "es" http://cssguidelin.es/#specificity und bezog mich mit dem Kommentar noch auf:

> Zudem sehe ich eine Gefahr bei einer Verlinkung seiner Seite, denn in einigen Dingen sind unsere Ansätze nicht deckungsgleich. Das könnte zu Missverständnissen führen, wenn man über http://cssguidelin.es/#specificity hinausliest.

2017-12-06 08:12 UTC, merged